trigger: none

name: PR-$(Date:yyyyMMdd)$(Rev:-r)
variables:
  tags: 'PR'
  run_slow_tests: false
  subrepo_types: 'libraries projects'

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: build.yml
