"""
Biological Knowledge Graph (BCKG) v1.0

This is the initial implementation of the BCKG API.

Generated by Python OpenAPI Parser v0.2.4
"""

from .client import *

from collections import namedtuple

__title__ = 'biological-knowledge-graph-bck-g'
__author__ = 'openapi-parser-0.2.4'
__license__ = 'Unlicensed'
__copyright__ = 'Copyright 2020 Station-B'
__version__ = '1.0'

VersionInfo = namedtuple('VersionInfo', 'major minor micro releaselevel serial')
version_info = VersionInfo(*__version__.split('.'), releaselevel='alpha', serial=0)

__all__ = \
[
    'version_info',
    '__title__',
    '__author__',
    '__license__',
    '__copyright__',
    '__version__',
]
__pdoc__ = { }
__pdoc_extras__ = [ ]

_submodules = \
[
    client,
]

for _submodule in _submodules:
    _submodule_name = _submodule.__name__.partition(f'{__name__}.')[-1]
    __all__.extend(_submodule.__all__)
    __pdoc__[_submodule_name] = True
    _submodule.__pdoc__ = getattr(_submodule, '__pdoc__', dict())
    _extras = getattr(_submodule, '__pdoc_extras__', list())
    for _element in _submodule.__all__:
        __pdoc__[_element] = _element in _extras

